@startuml

interface ElectricCar {
	
	+ charge(int percentage): void
	+ public function start(): bool;
}

class TeslaModelOne {

	+ charge(int percentage): void
	+ start(): bool
}

class TeslaModelOneDecorator {
	- ElectricCar

	+ charge(int percentage): void
	+ superCharge(int percentage): void
	+ start(): bool
}

TeslaModelOneDecorator o--- ElectricCar
ElectricCar <|--- TeslaModelOne
ElectricCar <|--- TeslaModelOneDecorator



@enduml